In [4]:
import numpy as np

In [ ]:
# 1. Create a numpy array of size 2 x 2
a = np.array([[1,2],[3,4]])
print(a)


[[1 2]
 [3 4]]


In [ ]:
# 2. Create a random numpy array of size 3 x 4
b = np.random.random((2,2))
print(b)

[[0.30479576 0.92010069]
 [0.50850365 0.6578732 ]]


In [ ]:
# 3. Create a numpy array of ones and a numpy array of zeros
n1 = np.ones((3,3))
print(n1)

print("")

n2 = np.zeros((3,3))
print(n2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 4. Create a random numpy array of size 6x3 and transpose it
c = np.random.random((6,3))
print(c)

print("")

print(c.T)

# random_array = np.random.random((6, 3))
# transposed_array = random_array.T


[[0.76814578 0.11409727 0.77087598]
 [0.12678942 0.78668416 0.50586673]
 [0.75809535 0.35770879 0.54047717]
 [0.96701385 0.16298121 0.16812198]
 [0.97840442 0.48206299 0.64061936]
 [0.29617366 0.14763295 0.37967667]]

[[0.76814578 0.12678942 0.75809535 0.96701385 0.97840442 0.29617366]
 [0.11409727 0.78668416 0.35770879 0.16298121 0.48206299 0.14763295]
 [0.77087598 0.50586673 0.54047717 0.16812198 0.64061936 0.37967667]]


In [14]:
# 5. Create two random numpy array of size n x p and p x m and then compute the dot product
n = 3
p = 4
m = 5

d = np.random.random((n,p))
print("Array 1: \n",d)

e = np.random.random((p,m))
print("Array 2: \n",e)


print(" ")
dot_product = np.dot(d,e)
print("Dot product: \n",e)




Array 1: 
 [[0.00152327 0.16790353 0.36643483 0.34188501]
 [0.77800024 0.60903608 0.16397725 0.26570953]
 [0.37951854 0.22043628 0.93031387 0.34250179]]
Array 2: 
 [[0.54518412 0.05593237 0.23719117 0.89520373 0.59513357]
 [0.6603929  0.87946569 0.91154073 0.1781498  0.00353782]
 [0.84839348 0.7690164  0.76334744 0.96183577 0.76595641]
 [0.26681152 0.0288506  0.32062804 0.90659667 0.92539924]]
 
Dot product: 
 [[0.54518412 0.05593237 0.23719117 0.89520373 0.59513357]
 [0.6603929  0.87946569 0.91154073 0.1781498  0.00353782]
 [0.84839348 0.7690164  0.76334744 0.96183577 0.76595641]
 [0.26681152 0.0288506  0.32062804 0.90659667 0.92539924]]


In [52]:
# 1. Clone your repository
!git clone https://github.com/zoeywongzixin/data-science-toolkit.git
%cd data-science-toolkit

# 2. Copy your notebook from Drive to repo
!cp "/content/drive/MyDrive/Colab Notebooks/Tutorial_3.ipynb" .

# 3. Configure GitHub credentials
import os
os.environ['GITHUB_TOKEN'] = "your_token_here"
os.environ['GITHUB_USERNAME'] = "zoeywongzixin"

# 4. Link remote with token
!git remote set-url origin https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/data-science-toolkit.git

# 5. Add, commit, and push
!git add Tutorial_3.ipynb
!git commit -m "Add Tutorial Week 3 notebook"
!git push origin main


Cloning into 'data-science-toolkit'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 12 (delta 1), reused 2 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (12/12), 4.27 KiB | 485.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
/content/drive/MyDrive/Colab Notebooks/data-science-toolkit
cp: cannot stat '/Colab': No such file or directory
cp: cannot stat 'Notebooks/Tutorial_3.ipynb': No such file or directory
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
fatal: could not read Username for 'https://github.com': No such device or address
